// Mock data for the application
// In a real app, this would be stored in a database

export const workers = [
  {
    id: "W-1001",
    name: "Ahmed Malik",
    department: "Assembly",
    shift: "Morning",
    status: "Active",
    performance: 95,
    email: "ahmed.malik@leoni.com",
    phone: "+1 (555) 123-4567",
    hireDate: "2021-05-15",
    position: "Senior Assembler",
    supervisor: "Maria Rodriguez",
    address: "123 Main Street, Anytown, CA 12345",
    emergencyContact: "Fatima Malik, +1 (555) 987-6543",
    notes: "Excellent worker with attention to detail. Consistently exceeds performance targets.",
  },
  {
    id: "W-1002",
    name: "Sofia Chen",
    department: "Quality Control",
    shift: "Night",
    status: "Active",
    performance: 92,
    email: "sofia.chen@leoni.com",
    phone: "+1 (555) 234-5678",
    hireDate: "2020-11-03",
    position: "Quality Inspector",
    supervisor: "James Wilson",
    address: "456 Oak Avenue, Somewhere, NY 67890",
    emergencyContact: "Li Chen, +1 (555) 876-5432",
    notes: "Thorough and methodical. Great attention to detail and quality standards.",
  },
  {
    id: "W-1003",
    name: "Carlos Rodriguez",
    department: "Logistics",
    shift: "Morning",
    status: "Active",
    performance: 88,
    email: "carlos.rodriguez@leoni.com",
    phone: "+1 (555) 345-6789",
    hireDate: "2021-02-20",
    position: "Logistics Coordinator",
    supervisor: "Sarah Johnson",
    address: "789 Pine Street, Elsewhere, TX 54321",
    emergencyContact: "Maria Rodriguez, +1 (555) 765-4321",
    notes: "Efficient and organized. Good at coordinating complex logistics operations.",
  },
  {
    id: "W-1004",
    name: "Fatima Al-Farsi",
    department: "Assembly",
    shift: "Evening",
    status: "On Leave",
    performance: 90,
    email: "fatima.alfarsi@leoni.com",
    phone: "+1 (555) 456-7890",
    hireDate: "2020-08-10",
    position: "Assembler",
    supervisor: "Ahmed Malik",
    address: "321 Cedar Road, Anytown, CA 12345",
    emergencyContact: "Khalid Al-Farsi, +1 (555) 654-3210",
    notes: "Skilled assembler with good attention to detail. Currently on medical leave.",
  },
  {
    id: "W-1005",
    name: "John Smith",
    department: "Maintenance",
    shift: "Morning",
    status: "Active",
    performance: 85,
    email: "john.smith@leoni.com",
    phone: "+1 (555) 567-8901",
    hireDate: "2019-11-15",
    position: "Maintenance Technician",
    supervisor: "Robert Chen",
    address: "567 Maple Avenue, Somewhere, NY 67890",
    emergencyContact: "Jane Smith, +1 (555) 543-2109",
    notes: "Experienced maintenance technician. Good at troubleshooting mechanical issues.",
  },
  {
    id: "W-1006",
    name: "Maria Garcia",
    department: "Assembly",
    shift: "Evening",
    status: "Active",
    performance: 91,
    email: "maria.garcia@leoni.com",
    phone: "+1 (555) 678-9012",
    hireDate: "2021-03-05",
    position: "Team Lead",
    supervisor: "James Wilson",
    address: "890 Elm Street, Elsewhere, TX 54321",
    emergencyContact: "Jose Garcia, +1 (555) 432-1098",
    notes: "Excellent team leader. Good at motivating team members and ensuring quality work.",
  },
  {
    id: "W-1007",
    name: "David Kim",
    department: "Quality Control",
    shift: "Morning",
    status: "Active",
    performance: 87,
    email: "david.kim@leoni.com",
    phone: "+1 (555) 789-0123",
    hireDate: "2020-06-22",
    position: "Quality Analyst",
    supervisor: "Sofia Chen",
    address: "432 Birch Lane, Anytown, CA 12345",
    emergencyContact: "Michelle Kim, +1 (555) 321-0987",
    notes: "Detail-oriented quality analyst. Good at identifying potential issues.",
  },
  {
    id: "W-1008",
    name: "Sarah Johnson",
    department: "Logistics",
    shift: "Night",
    status: "Inactive",
    performance: 78,
    email: "sarah.johnson@leoni.com",
    phone: "+1 (555) 890-1234",
    hireDate: "2019-09-15",
    position: "Logistics Manager",
    supervisor: "Robert Chen",
    address: "765 Spruce Court, Somewhere, NY 67890",
    emergencyContact: "Michael Johnson, +1 (555) 210-9876",
    notes: "Currently on extended leave. Previously managed logistics operations effectively.",
  },
]

// Updated computers data with more detailed information
export const computers = [
  {
    id: "PC-1001",
    hostname: "LEONI-ASSEMBLY-A1",
    ipAddress: "192.168.1.101",
    macAddress: "00:1A:2B:3C:4D:5E",
    location: "Assembly Line A",
    status: "Online",
    lastMaintenance: "2023-03-15",
    cpuUsage: 65,
    memoryUsage: 72,
    diskUsage: 58,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-04-01T06:30:00Z",
    assignedUser: "Ahmed Malik",
    department: "Assembly",
    notes: "Primary workstation for assembly line operations",
  },
  {
    id: "PC-1002",
    hostname: "LEONI-QC-B1",
    ipAddress: "192.168.1.102",
    macAddress: "00:1A:2B:3C:4D:5F",
    location: "Quality Control",
    status: "Online",
    lastMaintenance: "2023-03-10",
    cpuUsage: 45,
    memoryUsage: 58,
    diskUsage: 42,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-04-01T07:15:00Z",
    assignedUser: "Sofia Chen",
    department: "Quality Control",
    notes: "Quality control testing station",
  },
  {
    id: "PC-1003",
    hostname: "LEONI-LOG-C1",
    ipAddress: "192.168.1.103",
    macAddress: "00:1A:2B:3C:4D:60",
    location: "Logistics Office",
    status: "Offline",
    lastMaintenance: "2023-02-28",
    cpuUsage: 0,
    memoryUsage: 0,
    diskUsage: 65,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-03-31T08:00:00Z",
    assignedUser: "Carlos Rodriguez",
    department: "Logistics",
    notes: "Logistics coordination workstation - currently offline for maintenance",
  },
  {
    id: "PC-1004",
    hostname: "LEONI-ASSEMBLY-B1",
    ipAddress: "192.168.1.104",
    macAddress: "00:1A:2B:3C:4D:61",
    location: "Assembly Line B",
    status: "Online",
    lastMaintenance: "2023-03-12",
    cpuUsage: 78,
    memoryUsage: 85,
    diskUsage: 72,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-04-01T06:45:00Z",
    assignedUser: "Maria Garcia",
    department: "Assembly",
    notes: "High-performance workstation for complex assembly tasks",
  },
  {
    id: "PC-1005",
    hostname: "LEONI-ADMIN-A1",
    ipAddress: "192.168.1.105",
    macAddress: "00:1A:2B:3C:4D:62",
    location: "Manager's Office",
    status: "Online",
    lastMaintenance: "2023-03-05",
    cpuUsage: 32,
    memoryUsage: 45,
    diskUsage: 38,
    operatingSystem: "Windows 10 Enterprise",
    lastBootTime: "2023-04-01T08:30:00Z",
    assignedUser: "James Wilson",
    department: "Administration",
    notes: "Management workstation with access to all factory systems",
  },
  {
    id: "PC-1006",
    hostname: "LEONI-RECEP-A1",
    ipAddress: "192.168.1.106",
    macAddress: "00:1A:2B:3C:4D:63",
    location: "Reception",
    status: "Online",
    lastMaintenance: "2023-03-20",
    cpuUsage: 25,
    memoryUsage: 40,
    diskUsage: 30,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-04-01T07:00:00Z",
    assignedUser: "Reception Staff",
    department: "Administration",
    notes: "Front desk computer for visitor management",
  },
  {
    id: "PC-1007",
    hostname: "LEONI-QC-B2",
    ipAddress: "192.168.1.107",
    macAddress: "00:1A:2B:3C:4D:64",
    location: "Quality Control",
    status: "Maintenance",
    lastMaintenance: "2023-03-22",
    cpuUsage: 0,
    memoryUsage: 0,
    diskUsage: 55,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-03-31T16:45:00Z",
    assignedUser: "David Kim",
    department: "Quality Control",
    notes: "Secondary quality control station - currently undergoing scheduled maintenance",
  },
  {
    id: "PC-1008",
    hostname: "LEONI-ASSEMBLY-C1",
    ipAddress: "192.168.1.108",
    macAddress: "00:1A:2B:3C:4D:65",
    location: "Assembly Line C",
    status: "Online",
    lastMaintenance: "2023-03-08",
    cpuUsage: 70,
    memoryUsage: 65,
    diskUsage: 60,
    operatingSystem: "Windows 10 Pro",
    lastBootTime: "2023-04-01T06:30:00Z",
    assignedUser: "Fatima Al-Farsi",
    department: "Assembly",
    notes: "Specialized workstation for precision assembly tasks",
  },
]

// New model: UserVerification for tracking login status and admin rights
export const userVerifications = [
  {
    id: "UV-1001",
    userId: "U-101",
    userName: "Ahmed Malik",
    computerId: "PC-1001",
    loginStatus: "Active",
    loginTime: "2023-04-01T08:45:00Z",
    lastActivityTime: "2023-04-01T10:15:00Z",
    adminRights: true,
    accessLevel: "Administrator",
    ipAddress: "192.168.1.101",
    sessionDuration: 90, // in minutes
    notes: "Regular morning shift login",
  },
  {
    id: "UV-1002",
    userId: "U-102",
    userName: "Sofia Chen",
    computerId: "PC-1002",
    loginStatus: "Active",
    loginTime: "2023-04-01T07:30:00Z",
    lastActivityTime: "2023-04-01T09:45:00Z",
    adminRights: false,
    accessLevel: "Standard",
    ipAddress: "192.168.1.102",
    sessionDuration: 135, // in minutes
    notes: "Quality control system access",
  },
  {
    id: "UV-1003",
    userId: "U-103",
    userName: "Carlos Rodriguez",
    computerId: "PC-1003",
    loginStatus: "Inactive",
    loginTime: "2023-03-31T16:30:00Z",
    lastActivityTime: "2023-03-31T18:15:00Z",
    adminRights: false,
    accessLevel: "Standard",
    ipAddress: "192.168.1.103",
    sessionDuration: 105, // in minutes
    notes: "Evening shift logout - computer now offline",
  },
  {
    id: "UV-1004",
    userId: "U-104",
    userName: "Fatima Al-Farsi",
    computerId: "PC-1008",
    loginStatus: "Active",
    loginTime: "2023-04-01T08:15:00Z",
    lastActivityTime: "2023-04-01T10:00:00Z",
    adminRights: false,
    accessLevel: "Standard",
    ipAddress: "192.168.1.108",
    sessionDuration: 105, // in minutes
    notes: "Assembly line operations access",
  },
  {
    id: "UV-1005",
    userId: "U-105",
    userName: "James Wilson",
    computerId: "PC-1005",
    loginStatus: "Active",
    loginTime: "2023-04-01T08:30:00Z",
    lastActivityTime: "2023-04-01T10:30:00Z",
    adminRights: true,
    accessLevel: "Administrator",
    ipAddress: "192.168.1.105",
    sessionDuration: 120, // in minutes
    notes: "Management system access with full admin rights",
  },
]

// New model: VPNStatus for monitoring VPN connections
export const vpnStatuses = [
  {
    id: "VPN-1001",
    userId: "U-101",
    userName: "Ahmed Malik",
    connectionStatus: "Connected",
    connectionTime: "2023-04-01T07:30:00Z",
    disconnectionTime: null,
    ipAddress: "203.0.113.45",
    location: "Factory HQ",
    deviceType: "Workstation",
    encryptionLevel: "AES-256",
    protocol: "OpenVPN",
    bandwidth: 15.2, // in Mbps
    dataTransferred: 256, // in MB
    notes: "Secure connection for remote management",
  },
  {
    id: "VPN-1002",
    userId: "U-105",
    userName: "James Wilson",
    connectionStatus: "Connected",
    connectionTime: "2023-04-01T08:15:00Z",
    disconnectionTime: null,
    ipAddress: "203.0.113.72",
    location: "Home Office",
    deviceType: "Laptop",
    encryptionLevel: "AES-256",
    protocol: "OpenVPN",
    bandwidth: 22.8, // in Mbps
    dataTransferred: 178, // in MB
    notes: "Management access from home office",
  },
  {
    id: "VPN-1003",
    userId: "U-102",
    userName: "Sofia Chen",
    connectionStatus: "Disconnected",
    connectionTime: "2023-03-31T19:45:00Z",
    disconnectionTime: "2023-03-31T22:30:00Z",
    ipAddress: "203.0.113.89",
    location: "Remote Site",
    deviceType: "Laptop",
    encryptionLevel: "AES-256",
    protocol: "OpenVPN",
    bandwidth: 18.5, // in Mbps
    dataTransferred: 320, // in MB
    notes: "Evening access for quality control reports review",
  },
  {
    id: "VPN-1004",
    userId: "U-106",
    userName: "Robert Chen",
    connectionStatus: "Connected",
    connectionTime: "2023-04-01T09:00:00Z",
    disconnectionTime: null,
    ipAddress: "203.0.113.112",
    location: "Satellite Office",
    deviceType: "Workstation",
    encryptionLevel: "AES-256",
    protocol: "OpenVPN",
    bandwidth: 25.1, // in Mbps
    dataTransferred: 145, // in MB
    notes: "IT maintenance and monitoring",
  },
  {
    id: "VPN-1005",
    userId: "U-107",
    userName: "Maria Garcia",
    connectionStatus: "Disconnected",
    connectionTime: "2023-03-31T18:30:00Z",
    disconnectionTime: "2023-03-31T20:45:00Z",
    ipAddress: "203.0.113.134",
    location: "Home Office",
    deviceType: "Tablet",
    encryptionLevel: "AES-256",
    protocol: "OpenVPN",
    bandwidth: 12.7, // in Mbps
    dataTransferred: 95, // in MB
    notes: "Brief access for schedule review",
  },
]

// New model: VerificationTask for scheduling and tracking verification operations
export const verificationTasks = [
  {
    id: "VT-1001",
    taskName: "Weekly System Integrity Check",
    computerId: "PC-1001",
    computerName: "LEONI-ASSEMBLY-A1",
    assignedTo: "U-101",
    assigneeName: "Ahmed Malik",
    status: "Completed",
    priority: "High",
    scheduledTime: "2023-03-31T08:00:00Z",
    startTime: "2023-03-31T08:15:00Z",
    completionTime: "2023-03-31T09:30:00Z",
    verificationResult: "Passed",
    issuesFound: 0,
    actionsTaken: "Standard verification protocol followed, no issues detected",
    nextScheduledTime: "2023-04-07T08:00:00Z",
    notes: "Regular weekly verification of assembly line system",
  },
  {
    id: "VT-1002",
    taskName: "Monthly Security Audit",
    computerId: "PC-1005",
    computerName: "LEONI-ADMIN-A1",
    assignedTo: "U-105",
    assigneeName: "James Wilson",
    status: "In Progress",
    priority: "Critical",
    scheduledTime: "2023-04-01T09:00:00Z",
    startTime: "2023-04-01T09:15:00Z",
    completionTime: null,
    verificationResult: null,
    issuesFound: null,
    actionsTaken: "Comprehensive security audit in progress",
    nextScheduledTime: "2023-05-01T09:00:00Z",
    notes: "Monthly security verification of management systems",
  },
  {
    id: "VT-1003",
    taskName: "Quality Control System Check",
    computerId: "PC-1002",
    computerName: "LEONI-QC-B1",
    assignedTo: "U-102",
    assigneeName: "Sofia Chen",
    status: "Scheduled",
    priority: "Medium",
    scheduledTime: "2023-04-02T10:00:00Z",
    startTime: null,
    completionTime: null,
    verificationResult: null,
    issuesFound: null,
    actionsTaken: null,
    nextScheduledTime: null,
    notes: "Regular verification of quality control testing systems",
  },
  {
    id: "VT-1004",
    taskName: "Emergency System Recovery",
    computerId: "PC-1003",
    computerName: "LEONI-LOG-C1",
    assignedTo: "U-106",
    assigneeName: "Robert Chen",
    status: "Completed",
    priority: "Critical",
    scheduledTime: "2023-03-31T16:00:00Z",
    startTime: "2023-03-31T16:05:00Z",
    completionTime: "2023-03-31T18:30:00Z",
    verificationResult: "Fixed",
    issuesFound: 2,
    actionsTaken: "Disk errors repaired, system files restored from backup, hardware diagnostics performed",
    nextScheduledTime: "2023-04-02T09:00:00Z",
    notes: "Emergency response to system failure - follow-up verification scheduled",
  },
  {
    id: "VT-1005",
    taskName: "New Software Deployment Verification",
    computerId: "PC-1004",
    computerName: "LEONI-ASSEMBLY-B1",
    assignedTo: "U-101",
    assigneeName: "Ahmed Malik",
    status: "Scheduled",
    priority: "High",
    scheduledTime: "2023-04-03T08:00:00Z",
    startTime: null,
    completionTime: null,
    verificationResult: null,
    issuesFound: null,
    actionsTaken: null,
    nextScheduledTime: null,
    notes: "Verification of new assembly line software deployment",
  },
]

export const departments = [
  {
    id: "D-101",
    name: "Assembly",
    building: "Building A",
    manager: "Maria Rodriguez",
    employeeCount: 95,
    description: "Main assembly line operations for product manufacturing",
  },
  {
    id: "D-102",
    name: "Quality Control",
    building: "Building A",
    manager: "James Wilson",
    employeeCount: 45,
    description: "Quality assurance and testing of manufactured products",
  },
  {
    id: "D-103",
    name: "Logistics",
    building: "Building B",
    manager: "Robert Chen",
    employeeCount: 35,
    description: "Handling of incoming materials and outgoing products",
  },
  {
    id: "D-104",
    name: "Maintenance",
    building: "Building A",
    manager: "Sarah Johnson",
    employeeCount: 30,
    description: "Maintenance of equipment and facilities",
  },
  {
    id: "D-105",
    name: "Administration",
    building: "Building B",
    manager: "Michael Brown",
    employeeCount: 40,
    description: "Administrative and management functions",
  },
]

export const activities = [
  {
    id: "A-1001",
    type: "worker-checkin",
    description: "Ahmed Malik checked in for morning shift",
    timestamp: "2023-04-01T09:15:00Z",
    department: "Assembly Line A",
    icon: "user-check",
  },
  {
    id: "A-1002",
    type: "maintenance",
    description: "Scheduled maintenance completed on 5 workstations",
    timestamp: "2023-04-01T08:45:00Z",
    department: "IT Department",
    icon: "computer",
  },
  {
    id: "A-1003",
    type: "network-issue",
    description: "Brief network outage in Building C resolved",
    timestamp: "2023-04-01T08:30:00Z",
    department: "IT Department",
    icon: "wifi-off",
  },
  {
    id: "A-1004",
    type: "server-update",
    description: "Database server updated to latest version",
    timestamp: "2023-04-01T08:15:00Z",
    department: "IT Department",
    icon: "hard-drive",
  },
  {
    id: "A-1005",
    type: "worker-checkout",
    description: "Sofia Chen completed night shift",
    timestamp: "2023-04-01T07:00:00Z",
    department: "Quality Control",
    icon: "user-minus",
  },
  {
    id: "A-1006",
    type: "system-restart",
    description: "Production monitoring systems restarted",
    timestamp: "2023-04-01T06:30:00Z",
    department: "Operations",
    icon: "refresh-cw",
  },
  {
    id: "A-1007",
    type: "worker-checkin",
    description: "Jamal Wilson checked in for night shift",
    timestamp: "2023-04-01T06:00:00Z",
    department: "Logistics",
    icon: "user-check",
  },
]

export const users = [
  {
    id: "U-101",
    name: "Ahmed Malik",
    email: "ahmed.malik@leoni.com",
    role: "Administrator",
    lastActive: "2023-04-01T10:15:00Z",
    avatarUrl: null,
  },
  {
    id: "U-102",
    name: "Sofia Chen",
    email: "sofia.chen@leoni.com",
    role: "Manager",
    lastActive: "2023-04-01T08:30:00Z",
    avatarUrl: null,
  },
  {
    id: "U-103",
    name: "Carlos Rodriguez",
    email: "carlos.rodriguez@leoni.com",
    role: "Supervisor",
    lastActive: "2023-04-01T07:45:00Z",
    avatarUrl: null,
  },
  {
    id: "U-104",
    name: "Fatima Al-Farsi",
    email: "fatima.alfarsi@leoni.com",
    role: "Manager",
    lastActive: "2023-03-31T16:20:00Z",
    avatarUrl: null,
  },
  {
    id: "U-105",
    name: "James Wilson",
    email: "james.wilson@leoni.com",
    role: "Administrator",
    lastActive: "2023-04-01T10:30:00Z",
    avatarUrl: null,
  },
  {
    id: "U-106",
    name: "Robert Chen",
    email: "robert.chen@leoni.com",
    role: "IT Specialist",
    lastActive: "2023-04-01T09:45:00Z",
    avatarUrl: null,
  },
  {
    id: "U-107",
    name: "Maria Garcia",
    email: "maria.garcia@leoni.com",
    role: "Team Lead",
    lastActive: "2023-03-31T20:45:00Z",
    avatarUrl: null,
  },
]

export const productivityData = [
  {
    name: "Week 1",
    productivity: 85,
    efficiency: 78,
    downtime: 12,
  },
  {
    name: "Week 2",
    productivity: 88,
    efficiency: 82,
    downtime: 10,
  },
  {
    name: "Week 3",
    productivity: 91,
    efficiency: 85,
    downtime: 8,
  },
  {
    name: "Week 4",
    productivity: 89,
    efficiency: 83,
    downtime: 9,
  },
]

export const usageData = [
  { time: "6:00", usage: 45 },
  { time: "7:00", usage: 52 },
  { time: "8:00", usage: 78 },
  { time: "9:00", usage: 86 },
  { time: "10:00", usage: 90 },
  { time: "11:00", usage: 92 },
  { time: "12:00", usage: 85 },
  { time: "13:00", usage: 72 },
  { time: "14:00", usage: 80 },
]

export const departmentData = [
  { name: "Assembly", value: 95, color: "#4f46e5" },
  { name: "Quality Control", value: 45, color: "#10b981" },
  { name: "Logistics", value: 35, color: "#f59e0b" },
  { name: "Maintenance", value: 30, color: "#6366f1" },
  { name: "Administration", value: 40, color: "#ec4899" },
]
